obj-$(CONFIG_MACH_MSM8974_G3) += board-8974-g3.o board-8974-g3-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CTC_CN) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CUCC_CN) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_OPEN_HK) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g3-rfkill.o
